name: Deploy

on:
    push:
        branches: "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: "latest"

            - name: Install dependencies
              run: bun install

            - name: build
              env:
                  BASE_PATH: "/timer"
              run: |
                  bun run build
                  ls -la ./dist

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: production-files
                  path: ./dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: List Artifacts
              run: |
                  echo "::debug::Listing all artifacts..."
                  curl \
                   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   https://api.github.com/repos/${{ github.repository }}/actions/artifacts

            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy
              id: deployment
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
