name: Deploy

on:
    push:
        branches: "main"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # ... (other steps)

            - name: build
              env:
                  BASE_PATH: "/timer"
              run: |
                  bun run build
                  ls -la ./dist

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: production-files
                  path: ./dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v2
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy
              id: deployment
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
